// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zSyIa0sOLKpLApwbWfUX_colPRh-6nA',
    appId: '1:767814921407:web:1106c03cb7d5d4e8c7ea0a',
    messagingSenderId: '767814921407',
    projectId: 'chat-app-5f5d5',
    authDomain: 'chat-app-5f5d5.firebaseapp.com',
    storageBucket: 'chat-app-5f5d5.appspot.com',
    measurementId: 'G-WVWHQKW6L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDa2rro-TCffFXCTrb8aLz8UgP1ghHoDo',
    appId: '1:767814921407:android:87399d8db6d2d7f4c7ea0a',
    messagingSenderId: '767814921407',
    projectId: 'chat-app-5f5d5',
    storageBucket: 'chat-app-5f5d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMphqKwUsqgwiyH7bm7JKmZlCfXqOBs-w',
    appId: '1:767814921407:ios:6be5c6957c3dfcd1c7ea0a',
    messagingSenderId: '767814921407',
    projectId: 'chat-app-5f5d5',
    storageBucket: 'chat-app-5f5d5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
